apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-rc
  labels:
    app: web
spec:
  template:
    metadata:
      name: firstpod
      labels:
        tier: frontend
    spec:
      containers:
        - name: appcontainer
          image: vigneshdayalan/kube-demo
  replicas: 6
    